apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: aline
  labels:
    component: gateway
spec:
  selector:
    matchLabels:
      component: gateway
  template:
    metadata:
      labels:
        component: gateway
    spec:
      containers:
      - name: gateway
        image: sebastianom/gateway
        env:
        - name: APP_PORT
          value: "8080"
        - name: DB_USERNAME
          value: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: DB_PASSWORD
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: alinedb
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: encrypt-key
              key: ENCRYPT_SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-key
              key: JWT_SECRET_KEY
        - name: APP_SERVICE_HOST
          value: server-cluster-ip
        - name: PORTAL_LANDING
          value: "4200"
        - name: PORTAL_DASHBOARD
          value: "3007"
        - name: PORTAL_ADMIN
          value: "3000"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
