apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-microservice-${LABEL_VERSION}
  namespace: aline
  labels:
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: deployment
      version: ${LABEL_VERSION}
  template:
    metadata:
      labels:
        component: deployment
        version: ${LABEL_VERSION}
    spec:
      containers:
      - name: account
        image: ${REPOSITORY}-account:${LABEL_VERSION}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8072
        env:
        - name: APP_PORT
          value: "8072"
        envFrom:
        - configMapRef:
            name: backend-configmap
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
