apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: aline
spec:
  type: LoadBalancer
  selector:
    component: gateway
  ports:
  - name: gateway
    port: 8080
    protocol: TCP
    targetPort: 8080