apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: aline
  labels:
    component: admin
spec:
  type: LoadBalancer
  selector:
    component: admin
  ports:
  - name: admin
    protocol: TCP
    port: 3000
    targetPort: 80